version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16.17.0
    commands:
      - echo Installing
  pre_build:
    commands:
      - echo Installing source NPM dependencies for Bazar-core.
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'